2020-09-10 23:37:48,402 ERROR: Exception on /reset_password_request [POST] [in /home/karomag/PycharmProjects/microblog/.venv/lib/python3.8/site-packages/flask/app.py:1891]
Traceback (most recent call last):
  File "/home/karomag/PycharmProjects/microblog/.venv/lib/python3.8/site-packages/flask_mail.py", line 492, in send
    message.send(connection)
  File "/home/karomag/PycharmProjects/microblog/.venv/lib/python3.8/site-packages/flask_mail.py", line 427, in send
    connection.send(self)
  File "/home/karomag/PycharmProjects/microblog/.venv/lib/python3.8/site-packages/flask_mail.py", line 188, in send
    self.host.sendmail(sanitize_address(envelope_from or message.sender),
  File "/usr/lib/python3.8/smtplib.py", line 856, in sendmail
    self.ehlo_or_helo_if_needed()
  File "/usr/lib/python3.8/smtplib.py", line 604, in ehlo_or_helo_if_needed
    if not (200 <= self.ehlo()[0] <= 299):
  File "/usr/lib/python3.8/smtplib.py", line 444, in ehlo
    self.putcmd(self.ehlo_msg, name or self.local_hostname)
  File "/usr/lib/python3.8/smtplib.py", line 371, in putcmd
    self.send(str)
  File "/usr/lib/python3.8/smtplib.py", line 363, in send
    raise SMTPServerDisconnected('please run connect() first')
smtplib.SMTPServerDisconnected: please run connect() first

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/karomag/PycharmProjects/microblog/.venv/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/karomag/PycharmProjects/microblog/.venv/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/karomag/PycharmProjects/microblog/.venv/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/karomag/PycharmProjects/microblog/.venv/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/karomag/PycharmProjects/microblog/.venv/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/karomag/PycharmProjects/microblog/.venv/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/karomag/PycharmProjects/microblog/app/routes.py", line 228, in reset_password_request
    send_password_reset_email(user)
  File "/home/karomag/PycharmProjects/microblog/app/email.py", line 34, in send_password_reset_email
    send_email(
  File "/home/karomag/PycharmProjects/microblog/app/email.py", line 24, in send_email
    mail.send(msg)
  File "/home/karomag/PycharmProjects/microblog/.venv/lib/python3.8/site-packages/flask_mail.py", line 492, in send
    message.send(connection)
  File "/home/karomag/PycharmProjects/microblog/.venv/lib/python3.8/site-packages/flask_mail.py", line 152, in __exit__
    self.host.quit()
  File "/usr/lib/python3.8/smtplib.py", line 988, in quit
    res = self.docmd("quit")
  File "/usr/lib/python3.8/smtplib.py", line 424, in docmd
    self.putcmd(cmd, args)
  File "/usr/lib/python3.8/smtplib.py", line 371, in putcmd
    self.send(str)
  File "/usr/lib/python3.8/smtplib.py", line 363, in send
    raise SMTPServerDisconnected('please run connect() first')
smtplib.SMTPServerDisconnected: please run connect() first
2020-09-10 23:39:30,237 INFO: Microblog startup [in /home/karomag/PycharmProjects/microblog/app/errors.py:60]
2020-09-10 23:39:39,012 ERROR: Exception on /reset_password_request [POST] [in /home/karomag/PycharmProjects/microblog/.venv/lib/python3.8/site-packages/flask/app.py:1891]
Traceback (most recent call last):
  File "/home/karomag/PycharmProjects/microblog/.venv/lib/python3.8/site-packages/flask_mail.py", line 492, in send
    message.send(connection)
  File "/home/karomag/PycharmProjects/microblog/.venv/lib/python3.8/site-packages/flask_mail.py", line 427, in send
    connection.send(self)
  File "/home/karomag/PycharmProjects/microblog/.venv/lib/python3.8/site-packages/flask_mail.py", line 188, in send
    self.host.sendmail(sanitize_address(envelope_from or message.sender),
  File "/usr/lib/python3.8/smtplib.py", line 856, in sendmail
    self.ehlo_or_helo_if_needed()
  File "/usr/lib/python3.8/smtplib.py", line 604, in ehlo_or_helo_if_needed
    if not (200 <= self.ehlo()[0] <= 299):
  File "/usr/lib/python3.8/smtplib.py", line 444, in ehlo
    self.putcmd(self.ehlo_msg, name or self.local_hostname)
  File "/usr/lib/python3.8/smtplib.py", line 371, in putcmd
    self.send(str)
  File "/usr/lib/python3.8/smtplib.py", line 363, in send
    raise SMTPServerDisconnected('please run connect() first')
smtplib.SMTPServerDisconnected: please run connect() first

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/karomag/PycharmProjects/microblog/.venv/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/karomag/PycharmProjects/microblog/.venv/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/karomag/PycharmProjects/microblog/.venv/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/karomag/PycharmProjects/microblog/.venv/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/karomag/PycharmProjects/microblog/.venv/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/karomag/PycharmProjects/microblog/.venv/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/karomag/PycharmProjects/microblog/app/routes.py", line 228, in reset_password_request
    send_password_reset_email(user)
  File "/home/karomag/PycharmProjects/microblog/app/email.py", line 34, in send_password_reset_email
    send_email(
  File "/home/karomag/PycharmProjects/microblog/app/email.py", line 24, in send_email
    mail.send(msg)
  File "/home/karomag/PycharmProjects/microblog/.venv/lib/python3.8/site-packages/flask_mail.py", line 492, in send
    message.send(connection)
  File "/home/karomag/PycharmProjects/microblog/.venv/lib/python3.8/site-packages/flask_mail.py", line 152, in __exit__
    self.host.quit()
  File "/usr/lib/python3.8/smtplib.py", line 988, in quit
    res = self.docmd("quit")
  File "/usr/lib/python3.8/smtplib.py", line 424, in docmd
    self.putcmd(cmd, args)
  File "/usr/lib/python3.8/smtplib.py", line 371, in putcmd
    self.send(str)
  File "/usr/lib/python3.8/smtplib.py", line 363, in send
    raise SMTPServerDisconnected('please run connect() first')
smtplib.SMTPServerDisconnected: please run connect() first
2020-09-10 23:46:39,587 INFO: Microblog startup [in /home/karomag/PycharmProjects/microblog/app/errors.py:60]
2020-09-10 23:47:38,472 INFO: Microblog startup [in /home/karomag/PycharmProjects/microblog/app/errors.py:60]
2020-09-10 23:49:50,311 INFO: Microblog startup [in /home/karomag/PycharmProjects/microblog/app/errors.py:60]
2020-09-10 23:53:39,121 INFO: Microblog startup [in /home/karomag/PycharmProjects/microblog/app/errors.py:60]
2020-09-10 23:56:39,493 INFO: Microblog startup [in /home/karomag/PycharmProjects/microblog/app/errors.py:60]
2020-09-10 23:57:53,164 INFO: Microblog startup [in /home/karomag/PycharmProjects/microblog/app/errors.py:60]
2020-09-11 00:11:47,062 INFO: Microblog startup [in /home/karomag/PycharmProjects/microblog/app/errors.py:60]
2020-09-11 22:42:24,899 INFO: Microblog startup [in /home/karomag/PycharmProjects/microblog/app/errors.py:60]
2020-09-11 22:44:55,252 INFO: Microblog startup [in /home/karomag/PycharmProjects/microblog/app/errors.py:60]
2020-09-11 22:46:09,419 INFO: Microblog startup [in /home/karomag/PycharmProjects/microblog/app/errors.py:60]
2020-09-11 22:47:16,761 INFO: Microblog startup [in /home/karomag/PycharmProjects/microblog/app/errors.py:60]
2020-09-11 22:59:32,983 INFO: Microblog startup [in /home/karomag/PycharmProjects/microblog/app/errors.py:60]
